# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_photo',
            field=models.ImageField(default='safgf', upload_to='media/menu_img'),
        ),
    ]
