# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_menu_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
