# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_auto_20181017_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
