# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0010_auto_20181020_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('item_photo', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
