# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0011_auto_20181020_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('item_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Customer')),
            ],
        ),
    ]
