# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0014_order_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('online_pay', 'online_pay')], default=1, max_length=20),
        ),
    ]
