# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0017_auto_20181022_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Customer'),
        ),
    ]
