# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0018_auto_20181022_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='UserName',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
