# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0019_auto_20181023_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_name',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
