# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0020_auto_20181023_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
