# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0022_remove_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=20),
        ),
    ]
