# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0023_auto_20181029_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
